import type { Metadata } from "next";

import "./globals.css";
import FloatingShape from "@/components/Background";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className="min-h-screen  flex items-center justify-center ">{children}</body>
  </html>
 );
}
